-- =============================================================================
-- Detectus v2 — Régularisation des dossiers santé historiques (NEUTRALISÉE)
--
-- (05/06/2026, revue Codex) Cette migration basculait en masse les dossiers
-- santé vers « Santé plus tard ». Elle est NEUTRALISÉE :
--   • historiquement elle ne touchait déjà aucun dossier (0 ligne en prod) ;
--   • comme la 004, une bascule en masse — rejouée ou basée sur les events
--     `deal_events` best-effort (insert client non attendu, erreurs avalées) —
--     pouvait écraser le tri manuel de l'équipe (incident santé du 05/06/2026).
--
-- La classification santé se fait désormais uniquement là où c'est atomique et
-- sûr : à l'import (`reponseVersDeal` → `statut='sante'`) et via l'IA en
-- arrière-plan (garde `statut='nouveau'`, ne touche jamais un dossier trié à la
-- main). Aucune opération sur les données ici.
--
-- Fichier conservé en no-op pour ne pas désaligner l'historique de migration
-- déjà appliqué en prod.
-- =============================================================================
